apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m
  chartRef:
    kind: OciRepository
    name: bitnami-nginx
    namespace: flux-system
  values:
    service:
      type: ClusterIP
    replicaCount: 1
