apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello-app
  namespace: default
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: go-hello-world
    namespace: flux-system
  values:
    replicaCount: 1
    service:
      type: ClusterIP
    args:
      - "-listen-addr=:3000"
      - "-log-format=json"
      - "-log-level=info"
      - "-otel-enabled"
    env:
      - name: "OTEL_SERVICE_NAME"
        value: "go-hello-world"
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
        value: "http://$(NODE_IP):4318"
